name: rgn2
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - conda-forge::pip
  - anaconda::tensorflow-gpu=1.15
  - anaconda::cudnn
  - pip:
      - biopython==1.73
      - coreapi==2.3.3
      - h5py==2.9.0
      - jupyter==1.0.0
      - numpy==1.19
      - pandas==1.1
      - python-Levenshtein==0.12.0
      - scikit-learn==1.0.0
      - scipy==1.2.0
      - seaborn==0.9.0
      - awscli==1.16.96
      - setproctitle==1.2.2